backend:
  name: git-gateway
  branch: master

media_folder: "public/uploads"
public_folder: "/uploads"

collections:
  - name: "noticias"
    label: "Noticias"
    folder: "src/content/noticias"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Título", name: "title", widget: "string", required: true, hint: "Ingresá el título de la noticia"}
      - { label: "Imagen", name: "image", widget: "image", required: true, hint: "Es la imagen que irá debajo del título"}
      - { label: "Contenido", name: "body", widget: "markdown", required: true, hint: "Ingresá el cuerpo de la noticia"}
      - { label: "Fecha", name: "date", widget: "string", hint: "Ingresá la fecha o período, ejemplo: 'julio, Buenos Aires' o 'primavera 2025'"}
      - { label: "Descripción", name: "description", widget: "string", required: true, hint: "Es la descripción que irá en el titular"}
      - { label: "Imagen del titular", name: "image2", widget: "image", required: true, hint: "Es la imagen que irá en el titular"}
